---
- name: install container
  docker_container:
    name: "{{docker_memcached_container_name}}"
    image: "memcached:{{docker_memcached_version}}"
    state: "{{docker_memcached_state}}"
    ports:
      - "{{docker_memcached_container_port}}:11211"